# Generated by Django 5.1.6 on 2025-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='person',
        ),
        migrations.AddField(
            model_name='participation',
            name='first_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='participation',
            name='last_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
